### PR TITLE
Move into NServiceBus namespace

### PR DESCRIPTION
**Pull request by danielmarbach**
Aligns the namespace in the public types with

https://github.com/Particular/PlatformArchitecture/blob/master/documentation/cross-cutting-concepts.md#downstream-components-rules

### CODE REVIEW

**Comment by timbussmann** [comment]
hm given that the current approach seems that the functions package is going to provide a dedicated subclass of this for the user, this wouldn't become really a user facing API and we could leave it in this namespace.

**Comment by timbussmann** [comment]
(see https://github.com/ParticularLabs/NServiceBus.AzureFunctions/pull/3/files#diff-26994d24979077f6a2690abb4149531d)

**Comment by danielmarbach** [comment]
Fair enough. But then let's enforce that design for now

https://github.com/ParticularLabs/NServiceBus.Serverless/pull/14

I did the minimal changes in that PR. We can always talk about making members virtual if necessary

**Comment by SeanFeldman** [comment]
Changes affecting both AWS and Functions TFs should have members of the TFs ping to help them pick up the changes and get up-to-speed. Similar to https://github.com/ParticularLabs/NServiceBus.Serverless/pull/11

**Comment by SeanFeldman** [comment]
Close this PR since #14 sounds like a better option.

**Pull request closed without merging**
